[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "tola"
version = "1.0.8"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "SQLAlchemy ~= 2.0",
    "boto3",
    "click",
    "duckdb ~= 1.0.0",
    "mysql-connector-python",
    "psycopg2", # PostgreSQL connector
    "python-ulid",
    "requests",
    "ruff",
    'importlib-metadata; python_version>="3.8"',
]

[project.scripts]
compare-pacbio-json="tola.compare_pacbio_json:cli"
data-processed="tola.data_processed:cli"
diff-mlwh="tola.diff_mlwh:cli"
duckdb-pacbio-report="tola.duckdb_pacbio_report:cli"
fetch-mlwh-seq-data="tola.fetch_mlwh_seq_data:cli"
load-mlwh-seq-data="tola.load_mlwh_seq_data:main"
pacbio-run-report="tola.pacbio_run_report:main"
status-duckdb="tola.status_sheets_to_duckdb:cli"
tqc="tola.tqc_command:cli"

[tool.setuptools.packages.find]
where = ["src"]
